# Generated by Django 4.2.1 on 2023-06-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_location_id_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
