# Generated by Django 4.2.1 on 2023-06-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
